### ISSUE TITLE
Configuration array incomplete since version 1.5.7

### ISSUE THREAD

**Issue by tobiasschaeferptb** [DMKEBUSINESSGMBH/typo3-mkphpids#1] opened 2016-04-01 17:01 UTC
Hello,

with version 1.5.5 the extension was working fine. After updating to 1.5.7 or later it doesn't detect attacks anymore and the debug_mode doesn't work too.
The system is:
SuSE Linux Enterprise Server 11 Service Pack 3
PHP 5.3.17
TYPO3 6.2.19

After some debugging I found that in IDS/Filter/Storage.php in line 117 an Exception "Unsupported filter type." is thrown because $type is empty.
So I printed $this->config and it looked like this:
Array
(
    [General] => Array
        (
            [exceptions] => Array
                (
                )
            [whitelist] => Array
                (
                )
            [json] => Array
                (
                )
            [html] => Array
                (
                )
            [base_path] => /srv/www/htdocs/t3_bms_62/typo3conf/ext/mkphpids/IDS/
        )
    [Logging] => Array
        (
            [table] => tx_mkphpids_log
            [recipients] => 
        )
    [Caching] => Array
        (
            [table] => tx_mkphpids_cache
        )
)

With version 1.5.5 the $this->config looks like this:
Array
(
    [General] => Array
        (
            [debug_mode] => 1
            [filter_type] => xml
            [use_base_path] => 1
            [filter_path] => default_filter.xml
            [tmp_path] => tmp
            [scan_keys] => 0
            [HTML_Purifier_Path] => IDS/vendors/htmlpurifier/HTMLPurifier.auto.php
            [HTML_Purifier_Cache] => IDS/vendors/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer
            [html] => Array
                (
                    [0] => __wysiwyg
                )

            [json] => Array
                (
                    [0] => POST.__jsondata
                )

            [whitelist] => Array
                (
                )

            [min_php_version] => 5.1.6
            [exceptions] => Array
                (
                    [0] => COOKIE.__utmz
                    [1] => COOKIE.__utmc
                    [2] => COOKIE.__gads
                    [3] => /COOKIE.*_session/i
                    [4] => /COOKIE._pk_ref_*/i
                    [5] => /POST.*.__hmac/i
                    [6] => /GET.*.__hmac/i
                    [7] => POST.EXAMPLE2
                    [8] => GET.EXAMPLE1
                )

            [base_path] => /srv/www/htdocs/t3_bms_62/typo3conf/ext/mkphpids/IDS/
        )

    [Logging] => Array
        (
            [email] => intranet@ptb.de
            [path] => tmp/phpids_log.txt
            [envelope] => 
            [safemode] => 1
            [header] => From:  mkphpids@###SITEHOST### ###CRLF###
            [urlencode] => 1
            [allowed_rate] => 15
            [table] => tx_mkphpids_log
            [recipients] => intranet@ptb.de
        )

    [Caching] => Array
        (
            [caching] => file
            [expiration_time] => 600
            [path] => tmp/default_filter.cache
            [table] => tx_mkphpids_cache
        )
)

So since version 1.5.7 something is going wrong with setting up the config, at least on my system.
Do you have any ideas what could be the reason?

Cheers, Tobias

**Comment by hannesbochmann** [comment] 2016-04-11 08:22
Seems like the TypoScript configuration is not loaded. Are the files ext_typoscript_constants.txt and ext_typoscript_setup.txt present in the extension root?
Did you clear the TYPO3 caches? (in version 1.5.7 there were some changes how the extensions is executed, maybe this is the problem.)

**Comment by tobiasschaeferptb** [comment] 2016-04-11 14:53
Hello,

both files ext_typoscript_constants.txt and ext_typoscript_setup.txt are present and I cleared all TYPO3 caches. On a different server with the some TYPO3 and mkphpids versions it's working. On this server where it is working I changed the PHP version from 5.5.30 to 5.4.45 and to 5.3.29, since the server where the problem occurs is running with PHP 5.3.17. I can't change it to 5.3.17 because my provider doesn't offer it. And I can't change the PHP version on the server with the problem at all.
The versions of the extensions mkphpids is depending on are (on both servers):
mklib 1.0.10
rn_base 0.15.0
Is there something to set up for these 2 extensions?
I included the static template "MK PHPIDS (mkphpids)" and "MK Lib - Basics (mklib)" in the first page.
Is the order important or where it is included?

Cheers, Tobias

**Comment by hannesbochmann** [comment] 2016-04-12 07:29
The order should be no problem.
I think it's a problem with TYPO3 and not the extensions as the problem seems to be that the TypoScript configurations get not loaded which is done by the core automatically.
Can you check with some other extension that comes with ext_typoscript_constants.txt and ext_typoscript_setup.txt files if the TypoScript configuration isn't loaded, too?

**Comment by tobiasschaeferptb** [comment] 2016-05-19 14:50
After adding
page.8 < plugin.tx_mkphpids_pi1
to the TypoScript setup the extension is working as expected again. This line was removed from ext_typoscript_setup.txt with version 1.5.7

**Comment by hannesbochmann** [comment] 2016-05-20 05:46
Since version 1.5.7 mkphpids is no longer executed through the plugin configured via TypoScript. It's now executed through the hook $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/index_ts.php']['preprocessRequest'] to check for attacks as early as possible.
So could you please check if the configuration is loaded in Tx_Mkphpids_Hook_IndexTs Line 44. What's inside $typoScriptConfiguration?

**Comment by tobiasschaeferptb** [comment] 2016-05-20 10:29
Array
(
    [tt_content.] => Array
        (
        )

    [includeLibs] => typo3conf/ext/mkphpids/pi1/class.tx_mkphpids_pi1.php
    [userFunc] => tx_mkphpids_pi1->main
    [lib.] => 
)

**Comment by hannesbochmann** [comment] 2016-05-20 10:38
The TypoScript of the extension is indeed not present. Can you post what's inside $GLOBALS['TSFE']->tmpl->setup at this point? Has the page which you are on (check $GLOBALS['TSFE']->id for the page ID) really the TypoScript included? (you can check that with the template backend module)

**Comment by tobiasschaeferptb** [comment] 2016-05-20 12:09
At that point $GLOBALS['TSFE'] doesn't exist. When I print_r($GLOBALS);die();  in mkphpids/Classes/Hook/IndexTs.php in line 47 there is no $GLOBALS['TSFE'].
I updated mkphpids, mklib and rn_base to the current versions from TER (2.0.0, 2.0.2, 1.0.9). But this didn't solve the problem. The TypoScript templates are included.
![templates](https://cloud.githubusercontent.com/assets/18217214/15427297/61de294c-1e94-11e6-940d-a88ff399d599.png)

**Comment by hannesbochmann** [comment] 2016-05-20 12:37
I can reproduce this now. There seems to be some problem with the parsing of the TypoScript by TYPO3. Sometimes this does not work. I take a look at it.

**Comment by hannesbochmann** [comment] 2016-05-20 12:55
You found a serious bug. At the point where mkphpids is included at the moment it's possible that the TypoScript configuration is not loaded when the first page in the page tree does not include the TypoScript templates. I'm looking now for another entry point.
Till I committed a solution the only possiblity is to include page.8 < plugin.tx_mkphpids_pi1 again like you did.

**Comment by tobiasschaeferptb** [comment] 2016-05-20 13:02
What exactly do you mean by "first page"? The first child of the page with id 0? In my case this first child has the id 2 and is of type shortcut. This page does include the TypoScript templates from mkphpids and mklib.

**Comment by hannesbochmann** [comment] 2016-05-20 13:04
Yeah, that's what I mean. Maybe there is also a problem with shortcuts. Anyway the current integration through the hook is buggy and must be reworked.

**Closed** 2016-05-23 08:11 UTC

**Comment by hannesbochmann** [comment] 2016-05-23 08:18
Thanks for reporting this bug. I just uploaded version 2.0.1 to the TER. Could you please check with this version if everything works as expected again?

**Comment by tobiasschaeferptb** [comment] 2016-05-23 14:29
It's working now. Thanks for fixing the bug!
